#!/bin/bash

# uguushot
# Bash client for the popular screenshot service puush.me
# -------------------------------------------------------
# Author: Tama
# Original Version Author: Darwin (http://hpup.co)
# License: WTFPL, version 2


# Read command line arguments.
OPTIND=1

sleep 0.2 # Fix for rogue WMs/DEs.

while getopts "h?qchafwl" opt; do
    case "$opt" in
        a)  SHOT_MODE=a
            ;;
        f)  SHOT_MODE=f
            ;;
        w)  SHOT_MODE=w
            ;;
    esac
done

shift $((OPTIND-1))
[ "$1" = "--" ] && shift

SHOT_FILE=$@

# Generate a file name
if [ -z $SHOT_FILE ]; then
    SHOT_FILE="/tmp/ss-`date '+%d-%m-%Y-%H%M%S'`.png"
fi

# Take the screenshot if necessary.
case $SHOT_MODE in
    a) scrot -b -q 90 -s $SHOT_FILE;;
    w) scrot -b -d 2 -q 90 -u $SHOT_FILE;;
    f) scrot -b -q 90 $SHOT_FILE;;
esac

# Check if the screenshot was successful.
# If not, notify the user and exit the program.
if [ ! -e "$SHOT_FILE" ]; then
    exit 1
fi

# Upload the screenshot.
# Thanks github.com/blha303/puush-linux/ for assistance.
UGUU_URL=`curl -F "file=@$SHOT_FILE" "https://uguu.se/api.php?d=upload-tool"`

# Put the URL response in the clipboard
echo $UGUU_URL | xsel -b
